<?php
// French language translations for DRC Portal

return [
    
     // Global
    'site_name' => 'DRC Authenticator Global',
    'lang_en' => 'Anglais',
    'lang_fr' => 'Français',
    'already_registered_signin' => 'Déjà inscrit ? Se connecter',
    // Main portal strings
    'title' => 'Portail DRC',
    'sign_in' => 'Se connecter',
    'register' => 'S\'inscrire',
    'logout' => 'Déconnexion',
    'admin' => 'Admin',
    'customer' => 'Client',
    'activate' => 'Activer',
    'deactivate' => 'Désactiver',
    'error' => 'Erreur',
    'success' => 'Succès',
    'save' => 'Enregistrer',
    'cancel' => 'Annuler',
    'search' => 'Recherche',
    'no_records' => 'Aucun enregistrement trouv\'e',
    'email_sent' => 'Email envoy\'e',
    'email_failed' => 'Email non envoy\'e',
    'pending' => 'En attente',
    'active' => 'Actif',
    'disabled' => 'D\'sactiv\'e',
    'invited' => 'Invit\'e',
    'Register your lines & products once.' => 'Enregistrez vos gammes et produits une seule fois.',
    'The DRC portal holds the master data behind your serialized packs.'=>'Le portail DRC contient les données de référence de vos paquets sérialisés.',

    // Authentication pages
    'sign_in_title' => 'Se connecter',
    'sign_in_subtitle' => 'Utilisez l\'email et le mot de passe avec lesquels vous vous \'etes inscrit.',
    'new_account' => 'Nouveau sur DRC ? Cr\'eez un compte client',
    'create_customer_account' => 'Cr\'eer un compte client',
    'already_registered' => 'D\'ja inscrit ? Connectez-vous',

    // Register Page
    'customer_registration' => 'Inscription Client',
    'drc_customer_registration' => 'Inscription Client DRC',
    'registration_lead' => 'Parlez-nous de votre entreprise. Un administrateur examine chaque inscription, et vous recevrez un e-mail dès que votre compte sera actif.',
    'fix_highlighted_fields' => 'Veuillez corriger les champs en surbrillance ci-dessous.',
    'company' => 'Entreprise',
    'company_name' => 'Nom de l\'entreprise',
    'customer_type' => 'Type de client',
    'select_customer_type' => 'Sélectionner le type de client',
    'manufacturer' => 'Fabricant',
    'importer' => 'Importateur',
    'country' => 'Pays',
    'select_country' => 'Sélectionner un pays',
    'address' => 'Adresse',
    'contact' => 'Contact',
    'contact_person' => 'Personne à contacter',
    'contact_number' => 'Numéro de contact',
    'optional' => '(optionnel)',
    'signin_details' => 'Détails de connexion',
    'email_hint' => 'Vous l\'utiliserez pour vous connecter, et nous y enverrons les mises à jour du compte.',
    'password_hint' => 'Au moins 8 caractères, avec une lettre et un chiffre.',
    'confirm_password' => 'Confirmer le mot de passe',
    'submit_registration' => 'Soumettre l\'inscription',

    // Dashboard page
    'overview' => 'Aper\'cu',
    'welcome' => 'Bienvenue',
    'finish_registration' => 'Terminez ces \'etapes pour compl\'eter votre inscription.',
    'production_lines' => 'Lignes de production',
    'partners' => 'Partenaires',
    'products' => 'Produits',
    'enter_company_gln' => 'Entrez votre GLN d\'entreprise',
    'register_production_line' => 'Enregistrer une ligne de production',
    'add_importer' => 'Ajouter un importateur',
    'add_manufacturer' => 'Ajouter un fabricant',
    'register_product' => 'Enregistrer vos produits',

    // Lines page
    'production_lines_title' => 'Lignes de production',
    'add_production_line' => 'Ajouter une ligne',
    'your_lines' => 'Vos lignes',
    'line_name' => 'Nom de la ligne',
    'added' => 'Ajout\'e',
    'remove_line' => 'Supprimer cette ligne de production',
    'no_lines_yet' => 'Pas encore de lignes de production',
    'add_your_first_line' => 'Ajoutez votre premi\'ere ligne en utilisant le formulaire',

    // Partners page
    'partners_title' => 'Partenaires',
    'add_importer_manufacturer' => 'Ajouter un importateur/fabricant',
    'your_partners' => 'Vos partenaires',
    'partner_name' => 'Nom du partenaire',
    'gln' => 'GLN',
    'address' => 'Adresse',
    'remove_partner' => 'Supprimer ce partenaire',
    'no_partners_yet' => 'Pas encore de partenaires',
    'add_your_first_partner' => 'Ajoutez votre premier partenaire en utilisant le formulaire',

    // Products page
    'products_title' => 'Produits',
    'register_product' => 'Enregistrer un produit',
    'edit_product' => 'Modifier le produit',
    'registered_products' => 'Produits enregistr\'es',
    'product_name' => 'Nom du produit',
    'unit_gtin' => 'GTIN d\'unit\'e',
    'outer_gtin' => 'GTIN d\'emballage',
    'master_gtin' => 'GTIN de lot',
    'pallet_gtin' => 'GTIN de palette',
    'quantity' => 'Quantit\'e',
    'per' => 'par',
    'monthly' => 'Mensuel',
    'quarterly' => 'Trimestriel',
    'half_yearly' => ' semestriel',
    'yearly' => 'Annuel',
    'register_product' => 'Enregistrer le produit',
    'save_changes' => 'Sauvegarder les modifications',
    'cancel_editing' => 'Annuler la modification',

    // Admin pages
    'customers' => 'Clients',
    'pending_customers' => 'Clients en attente',
    'active_customers' => 'Clients actifs',
    'deactivated_customers' => 'Clients d\'sactiv\'s',
    'all_customers' => 'Tous les clients',
    'review_new_registrations' => 'Examinez les nouvelles inscriptions et g\'erez l\'acc\'es des clients.',
    'search_customers' => 'Rechercher une entreprise, un email ou un contact',
    'company' => 'Entreprise',
    'customer_type' => 'Type de client',
    'registered' => 'Inscrit',
    'status' => 'Statut',
    'review' => 'Examiner',
    'view' => 'Voir',

    // Customer details
    'registration_details' => 'D\'etails d\'inscription',
    'access' => 'Acc\'es',
    'activate_account' => 'Activer le compte',
    'deactivate_account' => 'D\'sactiver le compte',
    'reactivate_account' => 'R\'activer le compte',
    'account_activated' => 'Ce client peut se connecter et g\'erer ses lignes, partenaires et produits.',
    'account_deactivated' => 'Ce compte est d\'sactiv\'e et ne peut pas se connecter.',
    'production_lines_count' => 'Lignes de production',
    'partners_count' => 'Partenaires',
    'products_count' => 'Produits',

    // Admin management
    'admins_title' => 'Admins',
    'add_admin' => 'Ajouter un admin',
    'admin_username' => 'Nom d\'utilisateur',
    'admin_email' => 'Email',
    'admin_email_info' => 'Nous envoyons un lien d\'activation \'a cette adresse email. Ils choisiront leur propre mot de passe.',
    'add_admin_send_email' => 'Ajouter un admin et envoyer un email',
    'admin_added' => 'Admin ajout\'e. Un email d\'activation a \'et\'e envoy\'e.',
    'admin_added_no_email' => 'Admin ajout\'e, mais l\'email d\'activation n\'a pas pu \'etre envoy\'e. V\'erifiez les param\'etres d\'email.',
    'resend_invite' => 'Renvoyer l\'invitation',
    'deactivate_admin' => 'D\'sactiver cet admin',
    'reactivate_admin' => 'R\'activer cet admin',

    // Forms and buttons
    'save' => 'Enregistrer',
    'save_gln' => 'Sauvegarder le GLN',
    'add_line' => 'Ajouter une ligne',
    'add_partner' => 'Ajouter un partenaire',
    'remove' => 'Supprimer',
    'edit' => 'Modifier',
    'cancel' => 'Annuler',
    'submit' => 'Soumettre',
    'back' => 'Retour',
    'continue' => 'Continuer',

    // Messages and alerts
    'validation_error' => 'Veuillez corriger les champs signal\'es.',
    'alert_error' => 'Erreur',
    'alert_success' => 'Succ\'es',
    'registration_received' => 'Inscription re\'ue. Un administrateur examinera votre compte et nous vous enverrons un email une fois que celui-ci sera activ\'e.',
    'company_gln_saved' => 'GLN d\'entreprise sauvegard\'e.',
    'production_line_added' => 'Ligne de production "{name}" ajout\'ee.',
    'production_line_removed' => 'Ligne de production supprim\'ee.',
    'partner_added' => 'Partenaire "{name}" ajout\'e.',
    'partner_removed' => 'Partenaire supprim\'e.',
    'product_registered' => 'Produit "{name}" enregistr\'e.',
    'product_updated' => 'Produit modifi\'e.',
    'product_removed' => 'Produit supprim\'e.',

    // Validation messages
    'field_required' => 'Ce champ est requis.',
    'invalid_email' => 'Veuillez entrer une adresse email valide.',
    'email_too_long' => 'L\'adresse email est trop longue.',
    'password_too_short' => 'Le mot de passe doit contenir au moins 8 caract\'eres.',
    'password_no_letter' => 'Le mot de passe doit contenir au moins une lettre.',
    'password_no_number' => 'Le mot de passe doit contenir au moins un chiffre.',
    'company_name_invalid' => 'Entrez le nom de votre entreprise (2 \'a 150 caract\'eres).',
    'country_not_selected' => 'Veuillez s\'electer un pays.',
    'contact_person_invalid' => 'Entrez le nom de la personne de contact.',
    'contact_number_invalid' => 'Utilisez des chiffres, +, - ou des espaces, ou laissez ce champ vide.',
    'address_invalid' => 'Entrez votre adresse compl\'ete.',
    'gln_required' => 'Le GLN est requis.',
    'gln_invalid' => 'Le GLN doit contenir 13 chiffres.',
    'gtin_invalid' => 'Le GTIN doit contenir 8, 12, 13 ou 14 chiffres.',
    'quantity_invalid' => 'Entrez une quantit\'e sup\'erieure \'a z\'ero.',

    // Emails
    'new_registration' => 'Nouvelle inscription DRC : {company_name}',
    'new_customer_registered' => 'Un nouveau client s\'est inscrit et attend d\'etre activ\'e.',
    'account_activated_subject' => 'Votre compte DRC est activ\'e',
    'account_activated_body' => 'Votre compte est pr\'et \'a l\'emploi. Connectez-vous avec l\'email et le mot de passe avec lesquels vous vous \'etes inscrit.',
    'admin_invite_subject' => 'Activez votre compte admin DRC',
    'admin_invite_body' => 'Vous avez \'et\'e ajout\'e en tant qu\'administrateur du portail DRC. Activez votre compte en choisissant un mot de passe. Ce lien est valable pendant 48 heures.',

    // UI components
    'actions' => 'Actions',
    'view_details' => 'Voir les d\'etails',
    'edit' => 'Modifier',
    'delete' => 'Supprimer',
    'confirm_delete' => 'Êtes-vous sûr de vouloir supprimer cet article?',

    // Language selector
    'english' => 'Anglais',
    'french' => 'Français',

    // Misc
    'loading' => 'Chargement...',
    'please_wait' => 'Veuillez patienter...',
    'refresh' => 'Rafra\'icher',
    'close' => 'Fermer',
    
        // Industries
    'industry' => 'Industrie',
    'select_industry' => 'Sélectionnez votre industrie',
    'ind_tobacco' => 'Tabac',
    'ind_pharma' => 'Pharmaceutique',
    'ind_medical' => 'Dispositifs médicaux',
    'ind_cosmetics' => 'Cosmétiques et soins personnels',
    'ind_food_beverage' => 'Alimentation et boissons',
    'ind_dairy' => 'Produits laitiers',
    'ind_water' => 'Eau en bouteille',
    'ind_alcohol' => 'Alcool et spiritueux',
    'ind_auto' => 'Pièces automobiles',
    'ind_electronics' => 'Électronique et électroménager',
    'ind_apparel' => 'Vêtements et textiles',
    'ind_luxury' => 'Produits de luxe',
    'ind_agro' => 'Agrochimie et semences',
    'ind_logistics' => 'Logistique et chaîne d\'approvisionnement',
    'ind_other' => 'Autre',
];
?>