<?php
// English language translations for DRC Portal

return [
    
    
      // Global
    'site_name' => 'DRC Authenticator Global',
    'lang_en' => 'English',
    'lang_fr' => 'French',
    'already_registered_signin' => 'Already registered? Sign in',
    // Main portal strings
    'title' => 'DRC Portal',
    'sign_in' => 'Sign in',
    'register' => 'Register',
    'logout' => 'Logout',
    'admin' => 'Admin',
    'customer' => 'Customer',
    'activate' => 'Activate',
    'deactivate' => 'Deactivate',
    'error' => 'Error',
    'success' => 'Success',
    'save' => 'Save',
    'cancel' => 'Cancel',
    'search' => 'Search',
    'no_records' => 'No records found',
    'email_sent' => 'Email sent',
    'email_failed' => 'Email failed',
    'pending' => 'Pending',
    'active' => 'Active',
    'disabled' => 'Disabled',
    'invited' => 'Invited',

    // Authentication pages
    'sign_in_title' => 'Sign in',
    'sign_in_subtitle' => 'Use the email and password you registered with.',
    'new_account' => 'New to DRC? Create a customer account',
    'create_customer_account' => 'Create a customer account',
    'already_registered' => 'Already registered? Sign in',


    // Register Page
    'customer_registration' => 'Customer Registration',
    'drc_customer_registration' => 'DRC Customer Registration',
    'registration_lead' => 'Tell us about your company. An admin reviews every registration, and you will get an email once your account is active.',
    'fix_highlighted_fields' => 'Please fix the highlighted fields below.',
    'company' => 'Company',
    'company_name' => 'Company name',
    'customer_type' => 'Customer type',
    'select_customer_type' => 'Select customer type',
    'manufacturer' => 'Manufacturer',
    'importer' => 'Importer',
    'country' => 'Country',
    'select_country' => 'Select a country',
    'address' => 'Address',
    'contact' => 'Contact',
    'contact_person' => 'Contact person',
    'contact_number' => 'Contact number',
    'optional' => '(optional)',
    'signin_details' => 'Sign-in details',
    'email_hint' => 'You will use this to sign in, and we will send account updates here.',
    'password_hint' => 'At least 8 characters, with a letter and a number.',
    'confirm_password' => 'Confirm password',
    'submit_registration' => 'Submit registration',

    // Dashboard page
    'overview' => 'Overview',
    'welcome' => 'Welcome',
    'finish_registration' => 'Finish these steps to complete your registration.',
    'production_lines' => 'Production lines',
    'partners' => 'Partners',
    'products' => 'Products',
    'enter_company_gln' => 'Enter your company GLN',
    'register_production_line' => 'Register a production line',
    'add_importer' => 'Add an importer',
    'add_manufacturer' => 'Add a manufacturer',
    'register_product' => 'Register your products',

    // Lines page
    'production_lines_title' => 'Production lines',
    'add_production_line' => 'Add a line',
    'your_lines' => 'Your lines',
    'line_name' => 'Line name',
    'added' => 'Added',
    'remove_line' => 'Remove this production line',
    'no_lines_yet' => 'No production lines yet',
    'add_your_first_line' => 'Add your first line using the form',

    // Partners page
    'partners_title' => 'Partners',
    'add_importer_manufacturer' => 'Add an importer/manufacturer',
    'your_partners' => 'Your partners',
    'partner_name' => 'Partner name',
    'gln' => 'GLN',
    'address' => 'Address',
    'remove_partner' => 'Remove this partner',
    'no_partners_yet' => 'No partners yet',
    'add_your_first_partner' => 'Add your first partner using the form',

    // Products page
    'products_title' => 'Products',
    'register_product' => 'Register a product',
    'edit_product' => 'Edit product',
    'registered_products' => 'Registered products',
    'product_name' => 'Product name',
    'unit_gtin' => 'Unit GTIN',
    'outer_gtin' => 'Outer GTIN',
    'master_gtin' => 'Master GTIN',
    'pallet_gtin' => 'Pallet GTIN',
    'quantity' => 'Quantity',
    'per' => 'Per',
    'monthly' => 'Monthly',
    'quarterly' => 'Quarterly',
    'half_yearly' => 'Half-yearly',
    'yearly' => 'Yearly',
    'register_product' => 'Register product',
    'save_changes' => 'Save changes',
    'cancel_editing' => 'Cancel editing',

    // Admin pages
    'customers' => 'Customers',
    'pending_customers' => 'Pending customers',
    'active_customers' => 'Active customers',
    'deactivated_customers' => 'Deactivated customers',
    'all_customers' => 'All customers',
    'review_new_registrations' => 'Review new registrations and manage customer access.',
    'search_customers' => 'Search company, email or contact',
    'company' => 'Company',
    'customer_type' => 'Customer type',
    'registered' => 'Registered',
    'status' => 'Status',
    'review' => 'Review',
    'view' => 'View',

    // Customer details
    'registration_details' => 'Registration details',
    'access' => 'Access',
    'activate_account' => 'Activate account',
    'deactivate_account' => 'Deactivate account',
    'reactivate_account' => 'Reactivate account',
    'account_activated' => 'This customer can sign in and manage their lines, partners and products.',
    'account_deactivated' => 'This account is deactivated and cannot sign in.',
    'production_lines_count' => 'Production lines',
    'partners_count' => 'Partners',
    'products_count' => 'Products',

    // Admin management
    'admins_title' => 'Admins',
    'add_admin' => 'Add an admin',
    'admin_username' => 'Username',
    'admin_email' => 'Email',
    'admin_email_info' => 'We email an activation link here. They choose their own password.',
    'add_admin_send_email' => 'Add admin and send email',
    'admin_added' => 'Admin added. An activation email has been sent.',
    'admin_added_no_email' => 'Admin added, but the activation email could not be sent. Check the mail settings.',
    'resend_invite' => 'Resend invite',
    'deactivate_admin' => 'Deactivate this admin',
    'reactivate_admin' => 'Reactivate this admin',

    // Forms and buttons
    'save' => 'Save',
    'save_gln' => 'Save GLN',
    'add_line' => 'Add line',
    'add_partner' => 'Add partner',
    'remove' => 'Remove',
    'edit' => 'Edit',
    'cancel' => 'Cancel',
    'submit' => 'Submit',
    'back' => 'Back',
    'continue' => 'Continue',

    // Messages and alerts
    'validation_error' => 'Please fix the highlighted fields below.',
    'alert_error' => 'Error',
    'alert_success' => 'Success',
    'registration_received' => 'Registration received. An admin will review your account and we will email you as soon as it is activated.',
    'company_gln_saved' => 'Company GLN saved.',
    'production_line_added' => 'Production line "{name}" added.',
    'production_line_removed' => 'Production line removed.',
    'partner_added' => 'Partner "{name}" added.',
    'partner_removed' => 'Partner removed.',
    'product_registered' => 'Product "{name}" registered.',
    'product_updated' => 'Product updated.',
    'product_removed' => 'Product removed.',

    // Validation messages
    'field_required' => 'This field is required.',
    'invalid_email' => 'Enter a valid email address.',
    'email_too_long' => 'Email is too long.',
    'password_too_short' => 'Password must be at least 8 characters.',
    'password_no_letter' => 'Password must contain at least one letter.',
    'password_no_number' => 'Password must contain at least one number.',
    'company_name_invalid' => 'Enter your company name (2 to 150 characters).',
    'country_not_selected' => 'Select your country.',
    'contact_person_invalid' => 'Enter the contact person\'s name.',
    'contact_number_invalid' => 'Use digits, +, - or spaces, or leave this empty.',
    'address_invalid' => 'Enter your full address.',
    'gln_required' => 'GLN is required.',
    'gln_invalid' => 'GLN must be 13 digits.',
    'gtin_invalid' => 'GTIN must be 8, 12, 13 or 14 digits.',
    'quantity_invalid' => 'Enter a quantity greater than zero.',

    // Emails
    'new_registration' => 'New DRC registration: {company_name}',
    'new_customer_registered' => 'A new customer has registered and is waiting for activation.',
    'account_activated_subject' => 'Your DRC account is activated',
    'account_activated_body' => 'Your account is ready. Sign in with the email and password you registered with.',
    'admin_invite_subject' => 'Activate your DRC admin account',
    'admin_invite_body' => 'You have been added as an administrator of the DRC portal.',

    // UI components
    'actions' => 'Actions',
    'view_details' => 'View details',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'confirm_delete' => 'Are you sure you want to delete this item?',

    // Language selector
    'english' => 'English',
    'french' => 'Français',

    // Misc
    'loading' => 'Loading...',
    'please_wait' => 'Please wait...',
    'refresh' => 'Refresh',
    'close' => 'Close',
    
        // Industries
    'industry' => 'Industry',
    'select_industry' => 'Select your industry',
    'ind_tobacco' => 'Tobacco',
    'ind_pharma' => 'Pharmaceutical',
    'ind_medical' => 'Medical Devices',
    'ind_cosmetics' => 'Cosmetics & Personal Care',
    'ind_food_beverage' => 'Food & Beverage',
    'ind_dairy' => 'Dairy',
    'ind_water' => 'Bottled Water',
    'ind_alcohol' => 'Alcohol & Spirits',
    'ind_auto' => 'Automotive Parts',
    'ind_electronics' => 'Electronics & Appliances',
    'ind_apparel' => 'Apparel & Textiles',
    'ind_luxury' => 'Luxury Goods',
    'ind_agro' => 'Agrochemicals & Seeds',
    'ind_logistics' => 'Logistics & Supply Chain',
    'ind_other' => 'Other',
];
?>